---
booktitle: Conference on Parsimony and Learning
shortname: CPAL
volume: '280'
year: '2025'
start: &1 2025-03-24
end: 2025-03-27
published: 2025-06-15
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CPAL2025
month: 0
cycles: false
bibtex_editor: Chen, Beidi and Liu, Shijia and Pilanci, Mert and Su, Weijie and Sulam,
  Jeremias and Wang, Yuxiang and Zhu, Zhihui
editor:
- given: Beidi
  family: Chen
- given: Shijia
  family: Liu
- given: Mert
  family: Pilanci
- given: Weijie
  family: Su
- given: Jeremias
  family: Sulam
- given: Yuxiang
  family: Wang
- given: Zhihui
  family: Zhu
title: Proceedings of Machine Learning Research
description: |
  Conference on Parsimony and Learning
    Held in Stanford University, USA on 24-27 March 2025

  Published as Volume 280 by the Proceedings of Machine Learning Research on 15 June 2025.

  Volume Edited by:
    Beidi Chen
    Shijia Liu
    Mert Pilanci
    Weijie Su
    Jeremias Sulam
    Yuxiang Wang
    Zhihui Zhu

  Series Editors:
    Neil D. Lawrence
date_str: 24--27 Mar
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v280"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v280
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v280
email: ''
conference:
  name: Conference on Parsimony and Learning
  url: https://cpal.cc
  location: Stanford University, USA
  dates:
  - *1
  - 2025-03-25
  - 2025-03-26
  - 2025-03-27
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: CPAL25.bib
# Site settings
# Original source:  CPAL25.bib
